/**
 * Canonical list of collection table names.
 * Single source of truth — imported by storage.ts and both backends.
 */
export const COLLECTIONS = [
  'sessions',
  'credentials',
  'agents',
  'schedules',
  'tasks',
  'secrets',
  'provider_configs',
  'gateway_profiles',
  'skills',
  'learned_skills',
  'skill_suggestions',
  'supervisor_incidents',
  'run_reflections',
  'runtime_runs',
  'runtime_run_events',
  'runtime_estop',
  'connectors',
  'documents',
  'document_revisions',
  'webhooks',
  'model_overrides',
  'mcp_servers',
  'integrity_baselines',
  'webhook_logs',
  'projects',
  'activity',
  'webhook_retry_queue',
  'notifications',
  'chatrooms',
  'wallets',
  'wallet_transactions',
  'wallet_balance_history',
  'moderation_logs',
  'connector_health',
  'connector_outbox',
  'souls',
  'benchmarks',
  'approvals',
  'guardian_checkpoints',
  'browser_sessions',
  'watch_jobs',
  'delegation_jobs',
  'external_agents',
  'missions',
  'mission_events',
  'protocol_templates',
  'protocol_runs',
  'protocol_run_events',
  'provider_health',
  'swarm_snapshots',
  'main_loop_states',
] as const

export type StorageCollection = (typeof COLLECTIONS)[number]
